repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args:
          - "--maxkb=50000"
  - repo: local
    hooks:
    -   id: check-illegal-windows-names
        name: check illegal windows names
        language: fail
        entry: Illegal windows filenames detected
        verbose: True
        files: ':|<|>|;|,|\*|\?|\\'